server:
  port: 10010
spring:
  application:
    name: freevideo
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    username: root
    password: Zsp992033@
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://data.pin90.top:3306/free_video_website?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
  rabbitmq:
    host: data.pin90.top
    username: pin
    password: Zsp992033@
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
#      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true

